# Generated by Django 4.2 on 2023-04-11 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='uploads/instrutoresImages')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('slug_name', models.SlugField(blank=True, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_plano', models.ImageField(blank=True, null=True, upload_to='uploads/planoImages')),
                ('nome_plano', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
