# Generated by Django 4.2 on 2023-04-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_programa', models.ImageField(blank=True, null=True, upload_to='uploads/programaImages')),
                ('nome_programa', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='plano',
            old_name='descricao',
            new_name='beneficio1',
        ),
        migrations.AddField(
            model_name='plano',
            name='beneficio2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plano',
            name='beneficio3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plano',
            name='beneficio4',
            field=models.TextField(blank=True, null=True),
        ),
    ]
