# Generated by Django 4.2 on 2023-04-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_programa_rename_descricao_plano_beneficio1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='beneficio5',
            field=models.TextField(blank=True, null=True),
        ),
    ]
