# Generated by Django 4.2 on 2023-04-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_plano_beneficio5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='beneficio1',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='plano',
            name='beneficio2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='plano',
            name='beneficio3',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='plano',
            name='beneficio4',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='plano',
            name='beneficio5',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
